### PR TITLE
add place-holder-enabled

### PR DESCRIPTION
**Pull request by baov**
Allow user to select placeholder value

### CODE REVIEW

**Comment by baov** [comment]
Hello @jfmdev  can you check my PR ?
Have a nice day :)

**Comment by alismart** [comment]
Hello @baov 
Is this directive compatible with angular2?
I couldn't manage to install it on my angular2 project..

**Comment by jfmdev** [comment]
Hi @alismart,
Unfortunately, this directive is not compatible with Angular 2.
It's on the roadmap, but I can't give you a date.
Regards

**Comment by jfmdev** [comment]
Hello @baov  
Before merging your PR I have a question: 

*Why do you need a parameter for enable/disable the placeholder?*

I mean, if you don't want to use the placeholder, you just can give an empty value to `ng-placeholder`. I can't come up with an scenario in which you will need to enable/disable a placeholder in runtime.

Regards

**Comment by Yanntr** [comment]
Hello @jfmdev,

This new parameter _enable/disable_ the selection of the placeholder in runtime.

It can be usefull if you use this directive in a search form.
With this parameter enabled, the user can revert his selection in order to remove this criteria if he wants to.
Without this parameter, he must reload the page.

Regards

PS : I'm working with @baov

**Pull request merged**
